[entryPoints]
  [entryPoints.web]
  address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"
    scheme = "https"
  [entryPoints.websecure]
  address = ":443"
  
[providers.docker]
  exposedByDefault = false
  
[api]
  insecure = true
  dashboard = true
  
[certificatesResolvers.letsencrypt.acme]
  email = "adriancenizadev@gmail.com"
  storage = "acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web"
